# Generated by Django 2.0.1 on 2018-01-20 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='madified',
            new_name='modified',
        ),
    ]
