# Generated by Django 2.0.1 on 2018-01-20 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180120_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]$')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Pedido'),
        ),
    ]
