# Generated by Django 2.0.1 on 2018-01-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180120_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.IntegerField(max_length=11, verbose_name='Telefone'),
        ),
    ]
