# Generated by Django 2.0.1 on 2018-01-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180120_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Telefone'),
        ),
    ]
